name: "Nuke CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  ios-latest:
    name: Unit Tests (iOS 15.4, Xcode 13.3.1)
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          Scripts/test.sh -s "Nuke" -d "OS=15.4,name=iPhone 13 Pro"
          Scripts/test.sh -s "Nuke Extensions" -d "OS=15.4,name=iPhone 13 Pro"

  macos-latest:
    name: Unit Tests (macOS, Xcode 13.3.1)
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "arch=x86_64"
  tvos-latest:
    name: Unit Tests (tvOS 15.4, Xcode 13.3.1)
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "OS=15.4,name=Apple TV"
  watchos-latest:
    name: Unit Tests (watchOS 8.5, Xcode 13.3.1)
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "OS=8.5,name=Apple Watch Series 6 - 44mm"
  ios-xcode-13-2:
    name: Unit Tests (iOS 15.2, Xcode 13.2)
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "OS=15.2,name=iPhone 13 Pro"
  ios-thread-safety:
    name: Thread Safety Tests (TSan Enabled)
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -s "Nuke Thread Safety Tests" -d "OS=15.4,name=iPhone 13 Pro"
#  ios-memory-management-tests:
#    name: Memory Management Tests
#    runs-on: macOS-12
#    env:
#      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run Tests
#        run: Scripts/test.sh -s "Nuke Memory Management Tests" -d "OS=14.4,name=iPhone 12 Pro"
  ios-performance-tests:
    name: Performance Tests
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -s "Nuke Performance Tests" -d "OS=15.4,name=iPhone 13 Pro"
  swift-build:
    name: Swift Build (SPM)
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
  discover-typos:
    name: Discover Typos
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Discover typos
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart,inout,msdos,sur" --skip="./.build/*"

